### ISSUE TITLE
Streaming audio

### ISSUE THREAD

**Issue by renanaragao** [Odonno/RxSignalrStreams.Extensions#1]
Is it possible to capture the audio on the front and relay it to other customers, like a voip?

**Comment by Odonno** [comment]
@renanaragao I believe so. One of the use cases of SignalR streaming is video streaming, so I assume audio streaming is clearly feasible too.

Here is the perfect answer: https://stackoverflow.com/a/59458880

And if you want an official demo, check this video: https://youtu.be/YwezzKWrFuo?t=1354
